### PR TITLE
hw1 completed

### PR DESCRIPTION
**Pull request by imOnVacation**

### CODE REVIEW

**Comment by ethanSE** [comment]
Just FYI you can set up ESLint to help you conform to the Airbnb style guide. I'm guessing this may not be set up because it should warn you against using `i++` and suggest `i += 1`.

This looks good though. The only other thing I could find would be to suggest moving the initialization of the looping variable inside the for loop. This keeps the variable scoped to the loop, leaves the surrounding namespace alone, and makes it clear to readers that variable "i" is only used inside the loop.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for#lexical_declarations_in_the_initialization_block_is_scoped_to_the_for_loop

**Comment by imOnVacation** [comment]
> Just FYI you can set up ESLint to help you conform to the Airbnb style guide. I'm guessing this may not be set up because it should warn you against using `i++` and suggest `i += 1`.
> 
> This looks good though. The only other thing I could find would be to suggest moving the initialization of the looping variable inside the for loop. This keeps the variable scoped to the loop, leaves the surrounding namespace alone, and makes it clear to readers that variable "i" is only used inside the loop.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for#lexical_declarations_in_the_initialization_block_is_scoped_to_the_for_loop

Hey Ethan, Thanks for your feedback. I'm having trouble finding a guideline on setting up ESLint to make sure I'm writing the correct style. I look up [[Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)] and it didn't mention any installation instructions. Can you give me some directions on how to set up ESLint or where can I find resources, please? Thank you in advance!

**Review by sashetov — APPROVED** [review]
I've been following your commits and looks like you have fixed the things Ethan mentioned and I think everything else is good, so I think its good to merge.

**Comment by ethanSE** [comment]
> Updated: Nvm, I found it and successfully set it up through this [link](https://vicvijayakumar.com/blog/eslint-airbnb-style-guide-prettier).

I missed your reply but this looks like a better guide than the one I found. This looks good to me

**Review by ethanSE — APPROVED** [review]
Looks good

**Pull request merged**
